on:
  push:
    branches:
    - main
    - release/*
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: npm install, build
      - run: |
          npm install
          npm run build
          
          
      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          default_branch: 'main'
      
    
