on:
  push:
    branches:
    - main
    - release/*
  
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install, build and test
      - run: |
          npm install
          npm run build
          npm publish
      
    
